### ISSUE TITLE
Change docker port

### ISSUE THREAD

**Issue by Zrzzzz** [chainflag/solidctf#23]
how can I change port "8545" on my server

**Comment by Zrzzzz** [comment]
only change this I got
```
eth_faucet   | panic: cannot connect to web3 provider: 502 Bad Gateway: <html>
eth_faucet   | <head><title>502 Bad Gateway</title></head>
eth_faucet   | <body>
eth_faucet   | <center><h1>502 Bad Gateway</h1></center>
eth_faucet   | <hr><center>nginx/1.22.1</center>
eth_faucet   | </body>
eth_faucet   | </html>
eth_faucet   | 
eth_faucet   | 
eth_faucet   | goroutine 1 [running]:
eth_faucet   | github.com/chainflag/eth-faucet/cmd.Execute()
eth_faucet   |  /backend-build/cmd/server.go:58 +0x479
eth_faucet   | main.main()
eth_faucet   |  /backend-build/main.go:8 +0x25
fogeth       | INFO [07-06|17:54:58.548] Loaded most recent local header          number=949 hash=91e849..0adbd3 td=1899 age=46s
fogeth       | INFO [07-06|17:54:58.549] Loaded most recent local full block      number=337 hash=c0245f..c0454c td=675  age=1h14m53s
fogeth       | INFO [07-06|17:54:58.549] Loaded most recent local fast block      number=949 hash=91e849..0adbd3 td=1899 age=46s
eth_faucet exited with code 2
fogeth       | WARN [07-06|17:55:01.206] Loaded snapshot journal                  diffs=missing
fogeth       | INFO [07-06|17:55:01.217] Loaded local transaction journal         transactions=0 dropped=0
fogeth       | INFO [07-06|17:55:01.220] Regenerated local transaction journal    transactions=0 accounts=0
fogeth       | WARN [07-06|17:55:01.225] Switch sync mode from snap sync to full sync 
fogeth       | INFO [07-06|17:55:01.378] Gasprice oracle is ignoring threshold set threshold=2
fogeth       | WARN [07-06|17:55:01.385] Old unclean shutdowns found              count=3
fogeth       | WARN [07-06|17:55:01.386] Unclean shutdown detected                booted=2023-07-06T16:09:06+0000 age=1h45m55s
fogeth       | WARN [07-06|17:55:01.386] Unclean shutdown detected                booted=2023-07-06T16:10:30+0000 age=1h44m31s
fogeth       | WARN [07-06|17:55:01.386] Unclean shutdown detected                booted=2023-07-06T16:11:19+0000 age=1h43m42s
fogeth       | WARN [07-06|17:55:01.386] Unclean shutdown detected                booted=2023-07-06T16:13:34+0000 age=1h41m27s
fogeth       | WARN [07-06|17:55:01.386] Unclean shutdown detected                booted=2023-07-06T16:16:52+0000 age=1h38m9s
fogeth       | WARN [07-06|17:55:01.386] Unclean shutdown detected                booted=2023-07-06T16:19:11+0000 age=1h35m50s
fogeth       | WARN [07-06|17:55:01.386] Unclean shutdown detected                booted=2023-07-06T16:20:17+0000 age=1h34m44s
fogeth       | WARN [07-06|17:55:01.386] Unclean shutdown detected                booted=2023-07-06T16:35:32+0000 age=1h19m29s
fogeth       | WARN [07-06|17:55:01.386] Unclean shutdown detected                booted=2023-07-06T16:35:42+0000 age=1h19m19s
fogeth       | WARN [07-06|17:55:01.386] Unclean shutdown detected                booted=2023-07-06T16:38:13+0000 age=1h16m48s
fogeth       | WARN [07-06|17:55:01.386] Unclean shutdown detected                booted=2023-07-06T17:49:44+0000 age=5m17s
fogeth       | WARN [07-06|17:55:01.390] Engine API enabled                       protocol=eth
fogeth       | WARN [07-06|17:55:01.393] Engine API started but chain not configured for merge yet 
fogeth       | INFO [07-06|17:55:01.421] Starting peer-to-peer node               instance=Geth/v1.10.26-stable-e5eb32ac/linux-amd64/go1.18.8
challenge_1  | Traceback (most recent call last):
challenge_1  |   File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
challenge_1  |     httplib_response = self._make_request(
challenge_1  |   File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
challenge_1  |     self._validate_conn(conn)
challenge_1  |   File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
challenge_1  |     conn.connect()
challenge_1  |   File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 414, in connect
challenge_1  |     self.sock = ssl_wrap_socket(
challenge_1  |   File "/usr/local/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
challenge_1  |     ssl_sock = _ssl_wrap_socket_impl(
challenge_1  |   File "/usr/local/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
challenge_1  |     return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
challenge_1  |   File "/usr/local/lib/python3.10/ssl.py", line 513, in wrap_socket
challenge_1  |     return self.sslsocket_class._create(
challenge_1  |   File "/usr/local/lib/python3.10/ssl.py", line 1071, in _create
challenge_1  |     self.do_handshake()
challenge_1  |   File "/usr/local/lib/python3.10/ssl.py", line 1342, in do_handshake
challenge_1  |     self._sslobj.do_handshake()
challenge_1  | ConnectionResetError: [Errno 104] Connection reset by peer
challenge_1  | 
challenge_1  | During handling of the above exception, another exception occurred:
challenge_1  | 
challenge_1  | Traceback (most recent call last):
challenge_1  |   File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
challenge_1  |     resp = conn.urlopen(
challenge_1  |   File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
challenge_1  |     retries = retries.increment(
challenge_1  |   File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 550, in increment
challenge_1  |     raise six.reraise(type(error), error, _stacktrace)
challenge_1  |   File "/usr/local/lib/python3.10/site-packages/urllib3/packages/six.py", line 769, in reraise
challenge_1  |     raise value.with_traceback(tb)
challenge_1  |   File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
challenge_1  |     httplib_response = self._make_request(
challenge_1  |   File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
challenge_1  |     self._validate_conn(conn)
challenge_1  |   File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
challenge_1  |     conn.connect()
challenge_1  |   File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 414, in connect
challenge_1  |     self.sock = ssl_wrap_socket(
challenge_1  |   File "/usr/local/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
challenge_1  |     ssl_sock = _ssl_wrap_socket_impl(
challenge_1  |   File "/usr/local/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
challenge_1  |     return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
challenge_1  |   File "/usr/local/lib/python3.10/ssl.py", line 513, in wrap_socket
challenge_1  |     return self.sslsocket_class._create(
challenge_1  |   File "/usr/local/lib/python3.10/ssl.py", line 1071, in _create
challenge_1  |     self.do_handshake()
challenge_1  |   File "/usr/local/lib/python3.10/ssl.py", line 1342, in do_handshake
challenge_1  |     self._sslobj.do_handshake()
challenge_1  | urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
challenge_1  | 
challenge_1  | During handling of the above exception, another exception occurred:
challenge_1  | 
challenge_1  | Traceback (most recent call last):
challenge_1  |   File "/usr/local/lib/python3.10/site-packages/brownie/project/compiler/solidity.py", line 240, in _get_solc_version_list
challenge_1  |     AVAILABLE_SOLC_VERSIONS = solcx.get_installable_solc_versions()
challenge_1  |   File "/usr/local/lib/python3.10/site-packages/solcx/install.py", line 322, in get_installable_solc_versions
challenge_1  |     data = requests.get(BINARY_DOWNLOAD_BASE.format(_get_os_name(), "list.json"))
challenge_1  |   File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 73, in get
challenge_1  |     return request("get", url, params=params, **kwargs)
challenge_1  |   File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 59, in request
challenge_1  |     return session.request(method=method, url=url, **kwargs)
challenge_1  |   File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
challenge_1  |     resp = self.send(prep, **send_kwargs)
challenge_1  |   File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
challenge_1  |     r = adapter.send(request, **kwargs)
challenge_1  |   File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 547, in send
challenge_1  |     raise ConnectionError(err, request=request)
challenge_1  | requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
challenge_1  | 
challenge_1  | During handling of the above exception, another exception occurred:
challenge_1  | 
challenge_1  | Traceback (most recent call last):
challenge_1  |   File "<string>", line 11, in <module>
challenge_1  |   File "/usr/local/lib/python3.10/site-packages/brownie/project/main.py", line 780, in load
eth_faucet   | panic: cannot connect to web3 provider: 502 Bad Gateway: <html>
eth_faucet   | <head><title>502 Bad Gateway</title></head>
eth_faucet   | <body>
eth_faucet   | <center><h1>502 Bad Gateway</h1></center>
eth_faucet   | <hr><center>nginx/1.22.1</center>
eth_faucet   | </body>
challenge_1  |     return Project(name, project_path)
challenge_1  |   File "/usr/local/lib/python3.10/site-packages/brownie/project/main.py", line 188, in __init__
challenge_1  |     self.load()
challenge_1  |   File "/usr/local/lib/python3.10/site-packages/brownie/project/main.py", line 257, in load
challenge_1  |     self._compile(changed, self._compiler_config, False)
challenge_1  |   File "/usr/local/lib/python3.10/site-packages/brownie/project/main.py", line 100, in _compile
challenge_1  |     build_json = compiler.compile_and_format(
challenge_1  |   File "/usr/local/lib/python3.10/site-packages/brownie/project/compiler/__init__.py", line 105, in compile_and_format
challenge_1  |     find_solc_versions(solc_sources, install_needed=True, silent=silent)
challenge_1  |   File "/usr/local/lib/python3.10/site-packages/brownie/project/compiler/solidity.py", line 143, in find_solc_versions
challenge_1  |     available_versions, installed_versions = _get_solc_version_list()
challenge_1  |   File "/usr/local/lib/python3.10/site-packages/brownie/project/compiler/solidity.py", line 243, in _get_solc_version_list
challenge_1  |     raise ConnectionError("Solc not installed and cannot connect to GitHub")
challenge_1  | requests.exceptions.ConnectionError: Solc not installed and cannot connect to GitHub
eth_faucet   | </html>
eth_faucet   | 
eth_faucet   | 
eth_faucet   | goroutine 1 [running]:
eth_faucet   | github.com/chainflag/eth-faucet/cmd.Execute()
eth_faucet   |  /backend-build/cmd/server.go:58 +0x479
eth_faucet   | main.main()
eth_faucet   |  /backend-build/main.go:8 +0x25
eth_faucet   | panic: cannot connect to web3 provider: 502 Bad Gateway: <html>
eth_faucet   | <head><title>502 Bad Gateway</title></head>
eth_faucet   | <body>
eth_faucet   | <center><h1>502 Bad Gateway</h1></center>
eth_faucet   | <hr><center>nginx/1.22.1</center>
eth_faucet   | </body>
eth_faucet   | </html>
eth_faucet   | 
eth_faucet   | 
eth_faucet   | goroutine 1 [running]:
eth_faucet   | github.com/chainflag/eth-faucet/cmd.Execute()
eth_faucet   |  /backend-build/cmd/server.go:58 +0x479
eth_faucet   | main.main()
eth_faucet   |  /backend-build/main.go:8 +0x25
eth_faucet   | panic: cannot connect to web3 provider: 502 Bad Gateway: <html>
eth_faucet   | <head><title>502 Bad Gateway</title></head>
eth_faucet   | <body>
eth_faucet   | <center><h1>502 Bad Gateway</h1></center>
eth_faucet   | <hr><center>nginx/1.22.1</center>
eth_faucet   | </body>
eth_faucet   | </html>
eth_faucet   | 
eth_faucet   | 
eth_faucet   | goroutine 1 [running]:
eth_faucet   | github.com/chainflag/eth-faucet/cmd.Execute()
eth_faucet   |  /backend-build/cmd/server.go:58 +0x479
eth_faucet   | main.main()
```

**Comment by iczc** [comment]
I can't reproduce it, it seems your geth didn't start properly, try to delete the `data` directory and restart?

**Comment by Zrzzzz** [comment]
here is my docker-compose.yml
```
version: "3"
services:
  challenge:
    image: chainflag/solidctf:1.0.0
    restart: unless-stopped
    ports:
      - "7070:20000"
    env_file:
      - .env
    volumes:
      - ./flag.txt:/ctf/flag.txt
      - ./contracts:/ctf/contracts
      - ./challenge.yml:/ctf/challenge.yml

  ethereum:
    image: chainflag/fogeth:latest
    restart: unless-stopped
    container_name: fogeth
    ports:
      - "7777:8545"
    env_file:
      - .env
    volumes:
      - ./data:/data
      - ./logs:/var/log/nginx

  faucet:
    image: chainflag/eth-faucet:1.1.0
    restart: unless-stopped
    container_name: eth_faucet
    ports:
      - "7072:8080"
    links:
      - ethereum
    env_file:
      - .env
    command: -wallet.provider http://ethereum:8545 -wallet.privkey ${ALLOC_ADDRESS_PRIVATE_KEY} -faucet.minutes 1
    depends_on:
      - ethereum

```

and error log here.
[error.log](https://github.com/chainflag/solidctf/files/12015258/error.log)

Should I change the port in this line? https://github.com/chainflag/solidity-ctf-template/blob/401c6c470acdeada5eb64ba5bc258a85c503f43c/docker-compose.yml#L37C6-L37C6

or port in `.env` file.

**Comment by Zrzzzz** [comment]
Of course, the RUNNING version I'm using is that I didn't change the port of ethereum.

**Comment by iczc** [comment]
super weird, changing the external docker port shouldn't cause geth to fail to start. Or you can config port forwarding with iptables.

**Comment by Zrzzzz** [comment]
However, it works fine on my mac, maybe it is not compatible with my ubuntu server
